### ISSUE TITLE
New IANA registries are contrary to the main spec IANA section

### ISSUE THREAD

**Issue by rohan-wire** [mlswg/mls-extensions#3]
The extensions draft IANA section begins:

> This document requests the creation of the following new IANA registries:
>
>* MLS Extension Types ({{extended-mls-extension-types}})
>* MLS Proposal Types ({{extended-mls-proposal-types}})

This is contradictory to the clear language in the IANA considerations of the MLS protocol spec (example quoted from Section 17.2):

>[17.2. ](https://www.ietf.org/archive/id/draft-ietf-mls-protocol-16.html#section-17.2)[MLS Extension Types](https://www.ietf.org/archive/id/draft-ietf-mls-protocol-16.html#name-mls-extension-types)
>
>This registry lists identifiers for extensions to the MLS protocol. The extension type field is two bytes wide, so valid extension type values are in the range 0x0000 to 0xffff.

New extensions are supposed to be added to the **_EXISTING_** IANA registries.

**Comment by rohan-wire** [comment]
Submitted PR #4 to fix.

**Comment by raphaelrobert** [comment]
Closed via #4.
